@startuml
title Level 2 Implementation View

!define RECTANGLE class

skinparam package {
  BackgroundColor #87cefaff
  BorderColor black
}

package "Port Management System" {
  package UI
  package Planning
  package VVN_Service
  package Data_Service

  UI .down.> Planning 
  UI .down.> VVN_Service 
  UI .down.> Data_Service

  Planning .down.> VVN_Service
  VVN_Service .down.> Data_Service
}
@enduml