@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_TOP_DOWN()

title Level 2 - Logical View

interface admin  as "Administrator UI"
interface agent   as "Shipping Agent Representative UI"
interface officer as "Port Authority Officer UI"
interface operator as "Logistics Operator UI"
interface "External API" as API

' Interface externa
interface "WebUI" as webui_interface

System_Boundary(pms, "Port Management System") {

  ' Interfaces internas
  interface "BackendAPI" as backend_interface
  interface "PlanningService" as planning_interface

  Container(gui, "Web App (GUI)")
  Container(api, "Backend App", ".NET")
  Container(planning, "Planning Service", "Service")
  
  ' Ligação das interfaces aos containers
  gui -up- webui_interface
  gui -down- backend_interface
  api -up- backend_interface
  api -down- planning_interface
}

Rel(agent, webui_interface, "Uses")
Rel(officer, webui_interface, "Uses")
Rel(operator, webui_interface, "Uses")
Rel(admin, webui_interface, "Uses")

Rel(planning_interface, planning, "invokes")

Rel(planning, API, "Stores/loads planning data", "HTTP/REST")
@enduml