@startuml system_sequence_diagram
actor "Administrator" as User
participant "SPA (Frontend)" as Frontend
participant "Backend Module(s)" as Backend

User -> Frontend: Ask to assign role to user
activate Frontend
Frontend -> Backend: Request role assignment
activate Backend
Backend --> Frontend: Confirm role assigned
deactivate Backend

Frontend --> User: Notify role assignment success
deactivate Frontend
@enduml