using System.Collections.Generic;
using DDDSample1.Domain.Vessels.VesselVisitNotification.DTOs;

namespace DDDNetCore.Domain.Vessels.VesselInformation;

public class CargoManifestInputDto
{
    // ID is removed - it will be generated by the domain entity
    // public Guid Id { get; set; }

    public List<ContainerInputDto> Containers { get; set; } = new List<ContainerInputDto>();
}