// <auto-generated />
using System;
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20251022152713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DDDSample1.Domain.Categories.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DDDSample1.Domain.Docks.Dock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Depth")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("DDDSample1.Domain.Families.Family", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Representative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("DDDSample1.Domain.PhysicalResources.PhysicalResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedArea")
                        .HasColumnType("TEXT");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SetupTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhysicalResources");
                });

            modelBuilder.Entity("DDDSample1.Domain.PortInfrastructure.StorageArea.StorageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOccupancyTEUs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacityTEUs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("DDDSample1.Domain.Products.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DDDSample1.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("DDDSample1.Domain.StaffMembers.StaffMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalWindow")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.Vessel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Operator");

                    b.HasIndex("Owner");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.VesselVisitNotification.VesselVisitNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedDock")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotifications");
                });

            modelBuilder.Entity("DockVesselTypes", b =>
                {
                    b.Property<string>("AllowedVesselTypesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedVesselTypesId", "DockId");

                    b.HasIndex("DockId");

                    b.ToTable("DockVesselTypes");
                });

            modelBuilder.Entity("PhysicalResourceQualifications", b =>
                {
                    b.Property<string>("PhysicalResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationId")
                        .HasColumnType("TEXT");

                    b.HasKey("PhysicalResourceId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("PhysicalResourceQualifications");
                });

            modelBuilder.Entity("StaffMemberQualifications", b =>
                {
                    b.Property<string>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationId")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffMemberId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("StaffMemberQualifications");
                });

            modelBuilder.Entity("DDDSample1.Domain.Docks.Dock", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Shared.Location", "Location", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Coordinates")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Representative", b =>
                {
                    b.HasOne("DDDSample1.Domain.Organizations.Organization", null)
                        .WithMany("Representatives")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDSample1.Domain.PortInfrastructure.StorageArea.StorageArea", b =>
                {
                    b.OwnsMany("DDDNetCore.Domain.PortInfrastructure.StorageArea.StorageDockAssignment", "DockAssignments", b1 =>
                        {
                            b1.Property<Guid>("StorageAreaId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("DistanceMeters")
                                .HasColumnType("REAL");

                            b1.HasKey("StorageAreaId", "DockId");

                            b1.ToTable("StorageDockAssignment");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("DockAssignments");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.Vessel", b =>
                {
                    b.OwnsMany("DDDSample1.Domain.Vessels.CrewMember", "Crew", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CitizenId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("VesselId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("VesselId");

                            b1.ToTable("CrewMember");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.VesselVisitNotification.VesselVisitNotification", b =>
                {
                    b.HasOne("DDDSample1.Domain.Vessels.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DDDSample1.Domain.Vessels.VesselInformation.LoadingCargoMaterial", "LoadingCargo", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Vessels.VesselInformation.UnloadingCargoMaterial", "UnloadingCargo", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.Navigation("LoadingCargo");

                    b.Navigation("UnloadingCargo");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("DockVesselTypes", b =>
                {
                    b.HasOne("DDDSample1.Domain.Vessels.VesselType", null)
                        .WithMany()
                        .HasForeignKey("AllowedVesselTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhysicalResourceQualifications", b =>
                {
                    b.HasOne("DDDSample1.Domain.PhysicalResources.PhysicalResource", null)
                        .WithMany()
                        .HasForeignKey("PhysicalResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffMemberQualifications", b =>
                {
                    b.HasOne("DDDSample1.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.StaffMembers.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
