@startuml
title Level 2 Implementation View

!define RECTANGLE class

skinparam package {
  BackgroundColor #87cefaff
  BorderColor black
}

package "Port Management System" {
  package UI
  package Planning
  package VVN_Service
  package Data_Service

  UI --> Planning : uses Planning API
  UI --> VVN_Service : uses VVN API
  UI --> Data_Service : uses Data Service API

  Planning --> VVN_Service : obtains approved visits\n+ manifests
  VVN_Service --> Data_Service : obtains maindata\n
}
@enduml