// <auto-generated />
using System;
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    partial class DDDSample1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDDSample1.Domain.Authentication.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DDDSample1.Domain.Authentication.UserActivation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("UserActivations", (string)null);
                });

            modelBuilder.Entity("DDDSample1.Domain.Docks.Dock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<double>("Depth")
                        .HasColumnType("double precision");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxDraft")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AlternativeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Representative", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("DDDSample1.Domain.PhysicalResources.PhysicalResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedArea")
                        .HasColumnType("text");

                    b.Property<double>("Capacity")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SetupTime")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhysicalResources");
                });

            modelBuilder.Entity("DDDSample1.Domain.PortInfrastructure.StorageArea.StorageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CurrentOccupancyTEUs")
                        .HasColumnType("integer");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Heigth")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCapacityTEUs")
                        .HasColumnType("integer");

                    b.Property<int>("StorageAreaType")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("DDDSample1.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("DDDSample1.Domain.StaffMembers.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperationalWindow")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VesselTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Operator");

                    b.HasIndex("Owner");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.VesselType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxBays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRows")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.VesselVisitNotification.VesselVisitNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedDock")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DecisionTimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LoadTime")
                        .HasColumnType("integer");

                    b.Property<string>("OfficerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhysicalResourceIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RepresentativeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffMemberIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnloadTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotifications");
                });

            modelBuilder.Entity("DockVesselTypes", b =>
                {
                    b.Property<Guid>("AllowedVesselTypesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DockId")
                        .HasColumnType("uuid");

                    b.HasKey("AllowedVesselTypesId", "DockId");

                    b.HasIndex("DockId");

                    b.ToTable("DockVesselTypes");
                });

            modelBuilder.Entity("PhysicalResourceQualifications", b =>
                {
                    b.Property<Guid>("PhysicalResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uuid");

                    b.HasKey("PhysicalResourceId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("PhysicalResourceQualifications");
                });

            modelBuilder.Entity("StaffMemberQualifications", b =>
                {
                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uuid");

                    b.HasKey("StaffMemberId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("StaffMemberQualifications");
                });

            modelBuilder.Entity("DDDSample1.Domain.Authentication.UserActivation", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Authentication.UserID", "UserId", b1 =>
                        {
                            b1.Property<string>("UserActivationId")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("UserEmail");

                            b1.HasKey("UserActivationId");

                            b1.ToTable("UserActivations");

                            b1.WithOwner()
                                .HasForeignKey("UserActivationId");
                        });

                    b.Navigation("UserId");
                });

            modelBuilder.Entity("DDDSample1.Domain.Docks.Dock", b =>
                {
                    b.OwnsOne("DDDSample1.Domain.Shared.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("DockId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Coordinates")
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Representative", b =>
                {
                    b.HasOne("DDDSample1.Domain.Organizations.Organization", null)
                        .WithMany("Representatives")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDSample1.Domain.PortInfrastructure.StorageArea.StorageArea", b =>
                {
                    b.OwnsMany("DDDNetCore.Domain.PortInfrastructure.StorageArea.StorageDockAssignment", "DockAssignments", b1 =>
                        {
                            b1.Property<Guid>("StorageAreaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DockId")
                                .HasColumnType("uuid");

                            b1.Property<double>("DistanceMeters")
                                .HasColumnType("double precision");

                            b1.HasKey("StorageAreaId", "DockId");

                            b1.ToTable("StorageDockAssignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.OwnsOne("DDDSample1.Domain.Shared.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("StorageAreaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Coordinates")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("DockAssignments");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.Vessel", b =>
                {
                    b.OwnsMany("DDDSample1.Domain.Vessels.CrewMember", "Crew", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CitizenId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("VesselId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VesselId");

                            b1.ToTable("CrewMember");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("DDDSample1.Domain.Vessels.VesselVisitNotification.VesselVisitNotification", b =>
                {
                    b.HasOne("DDDSample1.Domain.Vessels.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DDDSample1.Domain.Vessels.VesselInformation.LoadingCargoMaterial", "LoadingCargo", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("uuid");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");

                            b1.OwnsMany("DDDSample1.Domain.Vessels.VesselInformation.CargoManifest", "Manifests", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("VesselVisitNotificationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("VesselVisitNotificationId");

                                    b2.ToTable("LoadingCargoManifests", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("VesselVisitNotificationId");

                                    b2.OwnsMany("DDDSample1.Domain.Vessels.VesselInformation.Container", "Containers", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uuid");

                                            b3.Property<Guid>("CargoManifestId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("ContentsDescription")
                                                .HasColumnType("text");

                                            b3.Property<double>("PayloadWeight")
                                                .HasColumnType("double precision");

                                            b3.HasKey("Id");

                                            b3.HasIndex("CargoManifestId");

                                            b3.ToTable("LoadingManifestContainers", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("CargoManifestId");
                                        });

                                    b2.Navigation("Containers");
                                });

                            b1.Navigation("Manifests");
                        });

                    b.OwnsOne("DDDSample1.Domain.Vessels.VesselInformation.UnloadingCargoMaterial", "UnloadingCargo", b1 =>
                        {
                            b1.Property<Guid>("VesselVisitNotificationId")
                                .HasColumnType("uuid");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");

                            b1.OwnsMany("DDDSample1.Domain.Vessels.VesselInformation.CargoManifest", "Manifests", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid?>("VesselVisitNotificationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("VesselVisitNotificationId");

                                    b2.ToTable("UnloadingCargoManifests", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("VesselVisitNotificationId");

                                    b2.OwnsMany("DDDSample1.Domain.Vessels.VesselInformation.Container", "Containers", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uuid");

                                            b3.Property<Guid>("CargoManifestId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("ContentsDescription")
                                                .HasColumnType("text");

                                            b3.Property<double>("PayloadWeight")
                                                .HasColumnType("double precision");

                                            b3.HasKey("Id");

                                            b3.HasIndex("CargoManifestId");

                                            b3.ToTable("UnloadingManifestContainers", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("CargoManifestId");
                                        });

                                    b2.Navigation("Containers");
                                });

                            b1.Navigation("Manifests");
                        });

                    b.Navigation("LoadingCargo");

                    b.Navigation("UnloadingCargo");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("DockVesselTypes", b =>
                {
                    b.HasOne("DDDSample1.Domain.Vessels.VesselType", null)
                        .WithMany()
                        .HasForeignKey("AllowedVesselTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhysicalResourceQualifications", b =>
                {
                    b.HasOne("DDDSample1.Domain.PhysicalResources.PhysicalResource", null)
                        .WithMany()
                        .HasForeignKey("PhysicalResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffMemberQualifications", b =>
                {
                    b.HasOne("DDDSample1.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.StaffMembers.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDSample1.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
